### ISSUE TITLE
How to uninstall this guardian

### ISSUE THREAD

**Issue by ZxakLol** [GalacticHypernova/Guardian#1]
Hello, please can you tell me how I can uninstall this guardian because it activates it accidentally and it doesn't let me open scripts that I want, so it bothers me. Can you tell me how to deactivate or uninstall it?

**Comment by GalacticHypernova** [comment]
Heya!
You can simply copy the whole script and then remove the auto generated section.
 It's not required in any way, shape, or form, however it's very much recommended for security, and I have just fixed an issue with fluxus so if you're using fluxus I recommend retrying.

**Comment by ZxakLol** [comment]
Hi but the guardian is not deleted  I already deleted the fluxus autoexect folder and the guardian is still working or what is the name of the folder to delete the guardian?

**Comment by GalacticHypernova** [comment]
If you want to put some script in auto execute, you can copy the script, create your own file, paste the script to it without guardian, and then execute your file, which would have only the script you want to execute.
